### ISSUE TITLE
Packages renamed?

### ISSUE THREAD

**Issue by daum** [AdRoll/batchiepatchie#3]
I'm trying to get a version of this running to test out for a deployment, however I can't get it to build.   I'm able to use the docker setup without issue (thanks!), however the actual deployment instructions and build fails on the go get, it looks like the repo was move from the SemanticSugar org to AdRoll.  For example https://github.com/SemanticSugar/batchiepatchie no longer exists but https://github.com/AdRoll/batchiepatchie does.  

I am very new to go so not sure if I'm doing something wrong or if there is an actual issue here.  Can you confirm either way?  I was able to build it by basically copying this repo into the gopath directory, based on the docker config.

Thanks for building this!

**Comment by Noeda** [comment]
You are not doing anything wrong.

We kind of messed up. I've pushed a change that removes all SemanticSugar references and renames them to AdRoll.

It used to be inside a private organization repo and looks like this slipped under the radar when we open sourced it. But this should work now.

Sorry for taking this long; it's only just now I noticed this issue.
