### ISSUE TITLE
AWS credentials not passed via env variables anymore

### ISSUE THREAD

**Issue by Fuuzetsu** [AdRoll/batchiepatchie#31]
The documentation says:

```
Our docker-compose.yml file passes environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as environment variables to the Batchiepatchie container so if you have these variables set up on your host system, the credentials should be passed correctly.
```

Perhaps it was true at one point but it doesn't seem to be now. It works if I do this:

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index cbd312e..7ec9aaf 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -5,6 +5,8 @@ services:
     environment:
       - BUILD_ENV=${BUILD_ENV}
       - BATCHIEPATCHIE_CONFIG=batchiepatchie-dockercompose-config.toml
+      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
+      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
     volumes:
       - .:/go/src/github.com/AdRoll/batchiepatchie
     ports:
@@ -57,4 +59,3 @@ networks:
     ipam:
       config:
        - subnet: "172.29.0.0/16"
-
```

**Comment by Noeda** [comment]
I think it should be harmless if we added your change to the docker-compose file. I opened PR for it https://github.com/AdRoll/batchiepatchie/pull/32

In the company where this was developed, every developer has a software on their laptop that adds a fake AWS IAM metadata service (it's called hologram) to get all credentials, so it's rare that anyone uses the environment variables to pass credentials around.

Big thanks for having enough patience to debug our crappy docker-compose file :)

**Comment by Noeda** [comment]
That PR #32 just got merged so I can close this issue. If you still have problems with this, re-open it.
