### ISSUE TITLE
Could not load API resposne jobs

### ISSUE THREAD

**Issue by rchojn** [AdRoll/batchiepatchie#34]
I followed docs and it appeared it does not work:

![image](https://user-images.githubusercontent.com/24687623/94931832-8538e200-04c8-11eb-8e7a-7aa9aecd5073.png)
frontend_1    | [HPM] Error occurred while trying to proxy request /api/v1/jobs/stats?start=1601046858&end=1601651658 from localhost:8080 to http://api:5454/ (ENOTFOUND) (https://nodejs.org/api/errors.html#errors_common_system_errors)

Any ideas?

**Comment by gvermillion** [comment]
I am also getting this error; however, when the page initially loads, I can see my queues listed. Within the first second, the red error bar pops up.

**Comment by eokeeffe** [comment]
Getting the same as well, is there a variable we need to change to make the api proxy work?

**Comment by davidlenz** [comment]
in my case was due to bad credentials:
- set region in batchiepatchie-dockercompose-config.toml
- set aws credentials in docker-compose.yml
solved it for me

**Comment by rchojn** [comment]
Thank you, @davidlenz solved the issue
