### ISSUE TITLE
Bug with "Next" pagination

### ISSUE THREAD

**Issue by muchovej** [AdRoll/batchiepatchie#4]
When scrolling through the pages, at times hitting the "Next >>" button at the bottom of the page adds "1" to the current string value of the page instead of the numerical value. 

i.e., if on page 3, and you hit next, it will get in a mode that takes you to page "31". if you hit next again, it will take you to page "311", always adding a string "1" to the page.

The "Previous <<" button works well.

**Comment by Noeda** [comment]
Fixed with PR #5 and merged.
