### ISSUE TITLE
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c go get]: exit code: 2

### ISSUE THREAD

**Issue by ShubhrikaSehgal** [AdRoll/batchiepatchie#50]
I am trying to run locally using the instructions. When executing the command docker-compose up. I am getting the following error. 
 > [batchiepatchie_api  5/11] RUN go get:
#14 336.3 # github.com/AdRoll/batchiepatchie
#14 336.3 ./logentries.go:9:47: not enough arguments in call to logentriesrus.NewLogentriesrusHook
#14 336.3       have (string)
#14 336.3       want (string, string)
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c go get]: exit code: 2

Not sure if i am doing something wrong

**Comment by JonathanAquino-NextRoll** [comment]
@ShubhrikaSehgal Could you try this again? We updated the version of Go and switched to Go modules.
