### ISSUE TITLE
Error with NewLogEntriesHook

### ISSUE THREAD

**Issue by blackary** [AdRoll/batchiepatchie#51]
```bash
# batchiepatchie
./logentries.go:9:47: not enough arguments in call to logentriesrus.NewLogentriesrusHook
        have (string)
        want (string, string)
```

NewLogEntriesHook changed to require 2 arguments https://github.com/jcftang/logentriesrus/commit/a32c4b116d99064957d79e84a7a29c2507a635da

**Comment by bh3791** [comment]
you can get past this by adding the extra parameter in the ./logentries.go file:
	le, err := logentriesrus.NewLogentriesrusHook("test", key)
but later I am running into another error,
      > [batchiepatchie_api  6/11] RUN go get -u github.com/tianon/gosu:                                                                                                                                 
     #13 19.32 # github.com/opencontainers/runc/libcontainer/system 
     #13 19.32 ../../opencontainers/runc/libcontainer/system/proc.go:70:16: undefined: os.ReadFile

It seems that batchiepatchie is not being maintained, the developers seem to be completely inactive for over a year.

**Comment by JonathanAquino-NextRoll** [comment]
@bh3791 we fixed the os.ReadFile error by upgrading the Go version.

docker compose up is now working.
